## Jest 测试异步代码

- 回调函数的测试

```js
test('the data is peanut butter', done => {
  function callback(data) {
    try {
      expect(data).toBe('peanut butter');
      done();
    } catch (error) {
      done(error);
    }
  }
  fetchData(callback);
});
```

- Promise

```js
test('the data is peanut butter', () => {
  return fetchData().then(data => {
    expect(data).toBe('peanut butter');
  });
});


// 如果你期望的 Promise 被拒绝，请使用​.catch​方法。
test('the fetch fails with an error', () => {
  expect.assertions(1);
  return fetchData().catch(e => expect(e).toMatch('error'));
});


// .resolves​ / ​.rejects​
// 你也可以在 ​expect ​语句中使用​ .resolves​ 匹配器，Jest 将等待此 Promise 解决。 如果 Promise 被拒绝，则测试将自动失败。
test('the data is peanut butter', () => {
  return expect(fetchData()).resolves.toBe('peanut butter');
});

// 一定不要忘记把整个断言作为返回值返回如果你忘了​return​语句的话，在 ​fetchData ​返回的这个 promise 变更为 resolved 状态、then() 有机会执行之前，测试就已经被视为已经完成了。
// 如果你期望 Promise 被拒绝，请使用.rejects匹配器。它参照工程 ​.resolves​ 匹配器。 如果 Promise 被拒绝，则测试将自动失败。

test('the fetch fails with an error', () => {
  return expect(fetchData()).rejects.toMatch('error');
});
```


- 异步/等待

```js
test('the data is peanut butter', async () => {
  const data = await fetchData();
  expect(data).toBe('peanut butter');
});
test('the fetch fails with an error', async () => {
  expect.assertions(1);
  try {
    await fetchData();
  } catch (e) {
    expect(e).toMatch('error');
  }
});

// 你可以将​async​和​await​与​.resolves​或结合​.rejects​使用​​。
test('the data is peanut butter', async () => {
    await expect(fetchData()).resolves.toBe('peanut butter');
});
test('the fetch fails with an error', async () => {
    await expect(fetchData()).rejects.toThrow('error');
});
```